spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/G-Maan/music-recommendation
          skip-ssl-validation: true
          search-paths: config
server:
  port: 8888
